# Generated by Django 4.2.4 on 2023-08-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=30)),
                ("coding_test", models.IntegerField()),
                ("writing_test", models.IntegerField()),
                ("reading_test", models.IntegerField()),
            ],
        ),
    ]
